// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSm0U4LeuVr2ZWey27J5VjWRnCuiE_D8',
    appId: '1:21429193352:web:089837079bb589856dad3d',
    messagingSenderId: '21429193352',
    projectId: 'flutterexam-56ece',
    authDomain: 'flutterexam-56ece.firebaseapp.com',
    storageBucket: 'flutterexam-56ece.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyrXH5reuvtkLiItn22HEGs7eWKJkI0zo',
    appId: '1:21429193352:android:e46ddaaefcb794706dad3d',
    messagingSenderId: '21429193352',
    projectId: 'flutterexam-56ece',
    storageBucket: 'flutterexam-56ece.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwo_b0VUlreRoIFEDv18k6o7yV3V-kJLI',
    appId: '1:21429193352:ios:22b7403c66e82e976dad3d',
    messagingSenderId: '21429193352',
    projectId: 'flutterexam-56ece',
    storageBucket: 'flutterexam-56ece.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwo_b0VUlreRoIFEDv18k6o7yV3V-kJLI',
    appId: '1:21429193352:ios:22b7403c66e82e976dad3d',
    messagingSenderId: '21429193352',
    projectId: 'flutterexam-56ece',
    storageBucket: 'flutterexam-56ece.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSm0U4LeuVr2ZWey27J5VjWRnCuiE_D8',
    appId: '1:21429193352:web:c7ca2f35e4a6a91f6dad3d',
    messagingSenderId: '21429193352',
    projectId: 'flutterexam-56ece',
    authDomain: 'flutterexam-56ece.firebaseapp.com',
    storageBucket: 'flutterexam-56ece.firebasestorage.app',
  );
}
